### PR TITLE
Update dependencies to latest upstream versions

### PR DESCRIPTION
**Pull request by rost**

### CODE REVIEW

**Review by cvik — COMMENTED** [review]
Are there no breaking changes in elli going from 2.x.x -> 3x.x.?

**Comment by cvik** [comment]
Fixes #6.

**Comment by rost** [comment]
Good point. I'm building a test suite to make sure. So let's pause this until the tests are merged.

**Comment by rost** [comment]
Rebased on https://github.com/cvik/heja/pull/10

No regressions.

**Review by cvik — DISMISSED** [review]
LGTM.

**Comment by rost** [comment]
Rebased on the new github actions flow.

**Review by cvik — APPROVED** [review]

**Pull request merged**
